### ISSUE TITLE
[ar-SA]: The group name are truncated in the search drop-down list on "Add tools" window

### ISSUE THREAD

**Issue by zholi** [OfficeDev/Office-365-People-Controls#13]
RTL bug
![ar-sa](https://cloud.githubusercontent.com/assets/3860596/8347858/5b133b52-1b3e-11e5-8571-7d3f19c64aa6.png)
![ar-sa-2](https://cloud.githubusercontent.com/assets/3860596/8347859/5c4198b6-1b3e-11e5-8cb0-5fb1af1a338d.png)

**Comment by lindalu-MSFT** [comment]
**Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
