### ISSUE TITLE
In IE, the format of focused record should be changed.

### ISSUE THREAD

**Issue by BrendaYang** [OfficeDev/Office-365-People-Controls#24]
![image](https://cloud.githubusercontent.com/assets/10627356/8474094/a0c0e2f6-20e0-11e5-89ec-ffee0e37836c.png)

**Comment by lindalu-MSFT** [comment]
@BrendaYang **Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
