### ISSUE TITLE
In IE10, the image doesn't show elegantly.

### ISSUE THREAD

**Issue by yihuacao** [OfficeDev/Office-365-People-Controls#35]
![image](https://cloud.githubusercontent.com/assets/11750350/8866396/91164f48-31ee-11e5-9c0c-683f1a3fc5c7.png)

**Comment by lindalu-MSFT** [comment]
@yihuacao **Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
