### ISSUE TITLE
Inline Persona should provide a constructed function that does not care the type of data.

### ISSUE THREAD

**Issue by whazmy** [OfficeDev/Office-365-People-Controls#43]
Inoder to create inlinePersona in AppChrome Control, I have to assign the value of "accountName" to "department", and make the value of jobTitle be "null". That does not make sense. The code is like this:
var personaObj = {};
personaObj.jobTitle = null;
personaObj.department = this.signedUserInfo.accountName;
personaObj.displayName = this.signedUserInfo.displayName;
personaObj.imgSrc = this.defaultImage;
if (this.signedUserInfo.imgSrc != null) {
          personaObj.ImageUrl = this.signedUserInfo.imgSrc;
}
Office.Controls.Persona.PersonaHelper.createInlinePersona(ele, personaObj);

**Comment by lindalu-MSFT** [comment]
**Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
