### ISSUE TITLE
Merge with PnP

### ISSUE THREAD

**Issue by pascalberger** [OfficeDev/Office-365-People-Controls#47]
I don't know the reasoning of this project, but wouldn't it make sense to merge this with the [Office365 Developer Patterns and Practices](https://github.com/OfficeDev/PnP) which also already provide a [server side](https://github.com/OfficeDev/PnP/tree/master/Components/Core.PeoplePicker) and [client side](https://github.com/OfficeDev/PnP/blob/master/Components/Core.JQuery/sp.peoplepicker.js.md) people picker? 

For users it is quite confusing to have to decide between different people pickers, all with their strengths and weaknesses. I missed this one for example since I wasn't aware about this project and therefore choose one from PnP, which on the other hand didn't use Office UI Fabric. And this one seems to be nicely designed with the Data Provider abstraction.

**Comment by zholi** [comment]
Hi Pascal,
Thanks for the suggestion. 
For this project, we are trying to provide a toolkit to help developers enable Office standard experience. We hope it could become a sample on how to consume and customize on [Office-UI-Fabric](https://github.com/OfficeDev/Office-UI-Fabric) and [Office 365 REST API](http://dev.office.com/chooseapiendpoint).
People controls are the most popular one that developers are asking for. So we pick it up as the 1st sample.

**Comment by pascalberger** [comment]
@zholi Thanks! But I still don't get why this couldn't be part of the PnP project which also tries to establish best practices for Office 365 developers. 

All this initiatives are great but it don't really helps if you as a develop has to search through different best practices to find the best best practice. Especially for People Controls for Office 365 there are currently this one, the two in PnP and the Office Web Widgets.

It would really be great if there would be a single solution for a specific problem published on a single location (for which I see PnP as the best with the most visibility at the moment)
