### ISSUE TITLE
When pasting in a user, the edit field doesn't expand properly

### ISSUE THREAD

**Issue by amitosharma** [OfficeDev/Office-365-People-Controls#48]
We are trying to fix the edit field expansion. When we paste a very long string it does not expand properly resulting in half text being shown even when there is enough space left in the box.
![assigntopeopleeditfieldafterpaste](https://cloud.githubusercontent.com/assets/7364946/11511375/a1e3865c-981d-11e5-9101-1940fb9d57c3.PNG)
Is there a way to make it expand automatically based on input pasted?

**Comment by zholi** [comment]
Hi Amitkumar,
Could you let me know the repro environment?

**Comment by lindalu-MSFT** [comment]
@amitosharma **Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
