### ISSUE TITLE
people picker not working on IE 11

### ISSUE THREAD

**Issue by aortiz-arroyo** [OfficeDev/Office-365-People-Controls#49]
I followed the steps of the sample application.  In IE11, when I type to search the name it shows an error saying 'Sorry, we're having trouble reaching the server.'  When I look at the console it says:

renewToken is failed:AADSTS70005: response_type 'token' is not enabled for the application
Trace ID: e6a1670a-9419-436e-a00d-2e6b1f2b1f00
Correlation ID: 2ba1eaa3-658b-4128-a2e8-88c68700119f
Timestamp: 2017-08-18 16:04:46Z

It works fine in Chrome, FireFox, and Edge.  Any thoughts?

**Comment by AbeGeMS** [comment]
I guess it might be related to cross domain limitation.

________________________________

**Comment by lindalu-MSFT** [comment]
@aortiz-arroyo **Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
