### ISSUE TITLE
Office.Controls.Persona.PersonaHelper.createInlinePersona function signature change?

### ISSUE THREAD

**Issue by etiennevandam** [OfficeDev/Office-365-People-Controls#50]
As per article on [Office 365 JavaScript controls](https://msdn.microsoft.com/en-us/office/office365/howto/javascript-controls) I have been pointing to https://controls.office.com/people/1.0/Office.Controls.People.min.js to implement the persona card for people on a custom control within SharePoint Online. This stopped working recently, not sure exactly when, but it is no longer available?
I therefore downloaded Office.Controls.Persona.js from this repo but the createInlinePersona function signature is different requiring an additional variable passed in called res. The comments within PersonaHelper function is as follows:
 /**
   * [createPersona description]
   * @param  {[type]} root         [description]
   * @param  {[type]} personObject same as peoplepicker's personObject queried from AAD
   * @param  {[type]} personaType  [description]
   * @return {[type]}              [description]
   */

Is it just me or was there a commit on changes that was not completed?

**Comment by lindalu-MSFT** [comment]
@etiennevandam **Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
