### ISSUE TITLE
People Picker does not have proper support for localization

### ISSUE THREAD

**Issue by Jaminba** [OfficeDev/Office-365-People-Controls#7]
In order to localize the people picker text, I have to hack the component.  Supported resource strings need to be clearly documented and accepted as parameters when initializing the component.  In addition, some of the resource strings are not meant to be localized at all and are in weird formats that make it very difficult for localization, like PeoplePickerResults = 'No results found||Show {0} result||Show {0} results'

This component must have proper, non hacky, localization support.

**Comment by lindalu-MSFT** [comment]
@Jaminba **Note:** This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. Therefore, I am closing this issue.
